printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
proseWrap: always
htmlWhitespaceSensitivity: css
endOfLine: lf
